version: '3'
services: 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
    ports:
      - 8080:80
    volumes:
      - "./data/phpmyadmin:/sessions"
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  web: 
    build: .
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
