version: '3'
services: 
  web: 
    build: .
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"